parameters:
    database_host:     db
    database_port:     3306
    database_name:     app
    database_user:     root
    database_password: secret123

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    session_memcached_host: memcached
    session_memcached_port: 11211
    session_memcached_prefix: session_
    session_memcached_expire: 3600

    secret: x6cxQnoDfKH7iiJksjFu
